// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/thing.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetTimeSeriesDatumRequest struct {
	TenantId             int64                `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SensorId             int64                `protobuf:"varint,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Value                float64              `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetTimeSeriesDatumRequest) Reset()         { *m = SetTimeSeriesDatumRequest{} }
func (m *SetTimeSeriesDatumRequest) String() string { return proto.CompactTextString(m) }
func (*SetTimeSeriesDatumRequest) ProtoMessage()    {}
func (*SetTimeSeriesDatumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{0}
}

func (m *SetTimeSeriesDatumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTimeSeriesDatumRequest.Unmarshal(m, b)
}
func (m *SetTimeSeriesDatumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTimeSeriesDatumRequest.Marshal(b, m, deterministic)
}
func (m *SetTimeSeriesDatumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTimeSeriesDatumRequest.Merge(m, src)
}
func (m *SetTimeSeriesDatumRequest) XXX_Size() int {
	return xxx_messageInfo_SetTimeSeriesDatumRequest.Size(m)
}
func (m *SetTimeSeriesDatumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTimeSeriesDatumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTimeSeriesDatumRequest proto.InternalMessageInfo

func (m *SetTimeSeriesDatumRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *SetTimeSeriesDatumRequest) GetSensorId() int64 {
	if m != nil {
		return m.SensorId
	}
	return 0
}

func (m *SetTimeSeriesDatumRequest) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SetTimeSeriesDatumRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type SetTimeSeriesDataRequest struct {
	Data                 []*SetTimeSeriesDatumRequest `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SetTimeSeriesDataRequest) Reset()         { *m = SetTimeSeriesDataRequest{} }
func (m *SetTimeSeriesDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetTimeSeriesDataRequest) ProtoMessage()    {}
func (*SetTimeSeriesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{1}
}

func (m *SetTimeSeriesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTimeSeriesDataRequest.Unmarshal(m, b)
}
func (m *SetTimeSeriesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTimeSeriesDataRequest.Marshal(b, m, deterministic)
}
func (m *SetTimeSeriesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTimeSeriesDataRequest.Merge(m, src)
}
func (m *SetTimeSeriesDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetTimeSeriesDataRequest.Size(m)
}
func (m *SetTimeSeriesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTimeSeriesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTimeSeriesDataRequest proto.InternalMessageInfo

func (m *SetTimeSeriesDataRequest) GetData() []*SetTimeSeriesDatumRequest {
	if m != nil {
		return m.Data
	}
	return nil
}

type SetTimeSeriesDataResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTimeSeriesDataResponse) Reset()         { *m = SetTimeSeriesDataResponse{} }
func (m *SetTimeSeriesDataResponse) String() string { return proto.CompactTextString(m) }
func (*SetTimeSeriesDataResponse) ProtoMessage()    {}
func (*SetTimeSeriesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{2}
}

func (m *SetTimeSeriesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTimeSeriesDataResponse.Unmarshal(m, b)
}
func (m *SetTimeSeriesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTimeSeriesDataResponse.Marshal(b, m, deterministic)
}
func (m *SetTimeSeriesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTimeSeriesDataResponse.Merge(m, src)
}
func (m *SetTimeSeriesDataResponse) XXX_Size() int {
	return xxx_messageInfo_SetTimeSeriesDataResponse.Size(m)
}
func (m *SetTimeSeriesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTimeSeriesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTimeSeriesDataResponse proto.InternalMessageInfo

func (m *SetTimeSeriesDataResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SetTimeSeriesDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SetSensorRequest struct {
	TenantId             int64    `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ThingId              int64    `protobuf:"varint,2,opt,name=thing_id,json=thingId,proto3" json:"thing_id,omitempty"`
	TypeId               int32    `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSensorRequest) Reset()         { *m = SetSensorRequest{} }
func (m *SetSensorRequest) String() string { return proto.CompactTextString(m) }
func (*SetSensorRequest) ProtoMessage()    {}
func (*SetSensorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{3}
}

func (m *SetSensorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSensorRequest.Unmarshal(m, b)
}
func (m *SetSensorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSensorRequest.Marshal(b, m, deterministic)
}
func (m *SetSensorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSensorRequest.Merge(m, src)
}
func (m *SetSensorRequest) XXX_Size() int {
	return xxx_messageInfo_SetSensorRequest.Size(m)
}
func (m *SetSensorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSensorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSensorRequest proto.InternalMessageInfo

func (m *SetSensorRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *SetSensorRequest) GetThingId() int64 {
	if m != nil {
		return m.ThingId
	}
	return 0
}

func (m *SetSensorRequest) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type SetSensorResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSensorResponse) Reset()         { *m = SetSensorResponse{} }
func (m *SetSensorResponse) String() string { return proto.CompactTextString(m) }
func (*SetSensorResponse) ProtoMessage()    {}
func (*SetSensorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{4}
}

func (m *SetSensorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSensorResponse.Unmarshal(m, b)
}
func (m *SetSensorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSensorResponse.Marshal(b, m, deterministic)
}
func (m *SetSensorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSensorResponse.Merge(m, src)
}
func (m *SetSensorResponse) XXX_Size() int {
	return xxx_messageInfo_SetSensorResponse.Size(m)
}
func (m *SetSensorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSensorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetSensorResponse proto.InternalMessageInfo

func (m *SetSensorResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SetSensorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SetThingRequest struct {
	TenantId             int64    `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetThingRequest) Reset()         { *m = SetThingRequest{} }
func (m *SetThingRequest) String() string { return proto.CompactTextString(m) }
func (*SetThingRequest) ProtoMessage()    {}
func (*SetThingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{5}
}

func (m *SetThingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetThingRequest.Unmarshal(m, b)
}
func (m *SetThingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetThingRequest.Marshal(b, m, deterministic)
}
func (m *SetThingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetThingRequest.Merge(m, src)
}
func (m *SetThingRequest) XXX_Size() int {
	return xxx_messageInfo_SetThingRequest.Size(m)
}
func (m *SetThingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetThingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetThingRequest proto.InternalMessageInfo

func (m *SetThingRequest) GetTenantId() int64 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *SetThingRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SetThingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetThingResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetThingResponse) Reset()         { *m = SetThingResponse{} }
func (m *SetThingResponse) String() string { return proto.CompactTextString(m) }
func (*SetThingResponse) ProtoMessage()    {}
func (*SetThingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba090fff2d0f56b8, []int{6}
}

func (m *SetThingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetThingResponse.Unmarshal(m, b)
}
func (m *SetThingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetThingResponse.Marshal(b, m, deterministic)
}
func (m *SetThingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetThingResponse.Merge(m, src)
}
func (m *SetThingResponse) XXX_Size() int {
	return xxx_messageInfo_SetThingResponse.Size(m)
}
func (m *SetThingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetThingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetThingResponse proto.InternalMessageInfo

func (m *SetThingResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SetThingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SetTimeSeriesDatumRequest)(nil), "protos.SetTimeSeriesDatumRequest")
	proto.RegisterType((*SetTimeSeriesDataRequest)(nil), "protos.SetTimeSeriesDataRequest")
	proto.RegisterType((*SetTimeSeriesDataResponse)(nil), "protos.SetTimeSeriesDataResponse")
	proto.RegisterType((*SetSensorRequest)(nil), "protos.SetSensorRequest")
	proto.RegisterType((*SetSensorResponse)(nil), "protos.SetSensorResponse")
	proto.RegisterType((*SetThingRequest)(nil), "protos.SetThingRequest")
	proto.RegisterType((*SetThingResponse)(nil), "protos.SetThingResponse")
}

func init() { proto.RegisterFile("protos/thing.proto", fileDescriptor_ba090fff2d0f56b8) }

var fileDescriptor_ba090fff2d0f56b8 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xbb, 0x0e, 0xd3, 0x30,
	0x14, 0xc5, 0xb4, 0xcd, 0xe3, 0x76, 0x00, 0x2c, 0x44, 0xdd, 0x30, 0x90, 0x66, 0xca, 0x94, 0x4a,
	0x45, 0x48, 0x6c, 0x48, 0xa8, 0x0c, 0x19, 0x18, 0x70, 0x3a, 0xc1, 0x80, 0x5c, 0x72, 0x09, 0x91,
	0x9a, 0x07, 0xb5, 0x83, 0xc4, 0x07, 0xf1, 0x6f, 0x7c, 0x06, 0xb2, 0xdd, 0xb4, 0x29, 0xa5, 0xa8,
	0xea, 0x96, 0xe3, 0x73, 0x73, 0x7d, 0x1e, 0x09, 0xd0, 0x76, 0xdf, 0xa8, 0x46, 0x2e, 0xd5, 0xb7,
	0xb2, 0x2e, 0x12, 0x03, 0xa8, 0x63, 0xcf, 0x82, 0x17, 0x45, 0xd3, 0x14, 0x3b, 0x5c, 0x1a, 0xb8,
	0xed, 0xbe, 0x2e, 0x55, 0x59, 0xa1, 0x54, 0xa2, 0x6a, 0xed, 0x60, 0xf4, 0x8b, 0xc0, 0x3c, 0x43,
	0xb5, 0x29, 0x2b, 0xcc, 0x70, 0x5f, 0xa2, 0x5c, 0x0b, 0xd5, 0x55, 0x1c, 0xbf, 0x77, 0x28, 0x15,
	0x7d, 0x0e, 0xbe, 0xc2, 0x5a, 0xd4, 0xea, 0x73, 0x99, 0x33, 0x12, 0x92, 0x78, 0xc4, 0x3d, 0x7b,
	0x90, 0xe6, 0x9a, 0x94, 0x58, 0xcb, 0x66, 0xaf, 0xc9, 0x87, 0x96, 0xb4, 0x07, 0x69, 0x4e, 0x9f,
	0xc2, 0xe4, 0x87, 0xd8, 0x75, 0xc8, 0x46, 0x21, 0x89, 0x09, 0xb7, 0x80, 0xbe, 0x06, 0xff, 0x28,
	0x80, 0x8d, 0x43, 0x12, 0x4f, 0x57, 0x41, 0x62, 0x25, 0x26, 0xbd, 0xc4, 0x64, 0xd3, 0x4f, 0xf0,
	0xd3, 0x70, 0xf4, 0x01, 0xd8, 0xdf, 0x32, 0x45, 0xaf, 0xf2, 0x15, 0x8c, 0x73, 0xa1, 0x04, 0x23,
	0xe1, 0x28, 0x9e, 0xae, 0x16, 0x76, 0x93, 0x4c, 0xae, 0xda, 0xe2, 0x66, 0x3c, 0x7a, 0x7f, 0xe9,
	0x5c, 0x70, 0x94, 0x6d, 0x53, 0x4b, 0xa4, 0xcf, 0xc0, 0x91, 0x4a, 0xa8, 0x4e, 0x1a, 0xdb, 0x1e,
	0x3f, 0x20, 0xca, 0xc0, 0xad, 0x50, 0x4a, 0x51, 0xa0, 0xb1, 0xec, 0xf3, 0x1e, 0x46, 0x5f, 0xe0,
	0x71, 0x86, 0x2a, 0x33, 0x01, 0xdc, 0x94, 0xdf, 0x1c, 0x3c, 0x53, 0xd9, 0x29, 0x3e, 0xd7, 0xe0,
	0x34, 0xa7, 0x33, 0x70, 0xd5, 0xcf, 0x16, 0x35, 0xa3, 0xf3, 0x9b, 0x70, 0x47, 0xc3, 0x34, 0x8f,
	0xde, 0xc1, 0x93, 0xc1, 0x25, 0x77, 0x6b, 0xfd, 0x04, 0x8f, 0xb4, 0x75, 0x7d, 0xdb, 0x4d, 0x52,
	0x67, 0xe0, 0x76, 0x12, 0x07, 0x45, 0x3b, 0x1a, 0xa6, 0x39, 0xa5, 0x30, 0xae, 0x45, 0x65, 0x5b,
	0xf6, 0xb9, 0x79, 0x8e, 0xd6, 0x26, 0x88, 0xc3, 0xf2, 0x7b, 0x25, 0xae, 0x7e, 0x13, 0x98, 0x98,
	0x1d, 0xf4, 0xa3, 0xf1, 0x7c, 0xde, 0x13, 0x0d, 0xaf, 0xb5, 0xdc, 0x7f, 0x15, 0xc1, 0xe2, 0x3f,
	0x13, 0x56, 0x55, 0xf4, 0x80, 0xbe, 0x05, 0xff, 0x98, 0x27, 0x65, 0x83, 0x37, 0xce, 0x7a, 0x0c,
	0xe6, 0xff, 0x60, 0x8e, 0x3b, 0xde, 0x80, 0xd7, 0xfb, 0xa5, 0xb3, 0xe1, 0xa5, 0x83, 0x78, 0x03,
	0x76, 0x49, 0xf4, 0x0b, 0xb6, 0xf6, 0x67, 0x7d, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0xed, 0x81,
	0x97, 0xdb, 0xc9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ThingClient is the client API for Thing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ThingClient interface {
	SetTimeSeriesData(ctx context.Context, in *SetTimeSeriesDataRequest, opts ...grpc.CallOption) (*SetTimeSeriesDataResponse, error)
	SetSensor(ctx context.Context, in *SetSensorRequest, opts ...grpc.CallOption) (*SetSensorResponse, error)
	SetThing(ctx context.Context, in *SetThingRequest, opts ...grpc.CallOption) (*SetThingResponse, error)
}

type thingClient struct {
	cc *grpc.ClientConn
}

func NewThingClient(cc *grpc.ClientConn) ThingClient {
	return &thingClient{cc}
}

func (c *thingClient) SetTimeSeriesData(ctx context.Context, in *SetTimeSeriesDataRequest, opts ...grpc.CallOption) (*SetTimeSeriesDataResponse, error) {
	out := new(SetTimeSeriesDataResponse)
	err := c.cc.Invoke(ctx, "/protos.Thing/SetTimeSeriesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingClient) SetSensor(ctx context.Context, in *SetSensorRequest, opts ...grpc.CallOption) (*SetSensorResponse, error) {
	out := new(SetSensorResponse)
	err := c.cc.Invoke(ctx, "/protos.Thing/SetSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thingClient) SetThing(ctx context.Context, in *SetThingRequest, opts ...grpc.CallOption) (*SetThingResponse, error) {
	out := new(SetThingResponse)
	err := c.cc.Invoke(ctx, "/protos.Thing/SetThing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThingServer is the server API for Thing service.
type ThingServer interface {
	SetTimeSeriesData(context.Context, *SetTimeSeriesDataRequest) (*SetTimeSeriesDataResponse, error)
	SetSensor(context.Context, *SetSensorRequest) (*SetSensorResponse, error)
	SetThing(context.Context, *SetThingRequest) (*SetThingResponse, error)
}

// UnimplementedThingServer can be embedded to have forward compatible implementations.
type UnimplementedThingServer struct {
}

func (*UnimplementedThingServer) SetTimeSeriesData(ctx context.Context, req *SetTimeSeriesDataRequest) (*SetTimeSeriesDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTimeSeriesData not implemented")
}
func (*UnimplementedThingServer) SetSensor(ctx context.Context, req *SetSensorRequest) (*SetSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSensor not implemented")
}
func (*UnimplementedThingServer) SetThing(ctx context.Context, req *SetThingRequest) (*SetThingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetThing not implemented")
}

func RegisterThingServer(s *grpc.Server, srv ThingServer) {
	s.RegisterService(&_Thing_serviceDesc, srv)
}

func _Thing_SetTimeSeriesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTimeSeriesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingServer).SetTimeSeriesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Thing/SetTimeSeriesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingServer).SetTimeSeriesData(ctx, req.(*SetTimeSeriesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Thing_SetSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingServer).SetSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Thing/SetSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingServer).SetSensor(ctx, req.(*SetSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Thing_SetThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetThingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingServer).SetThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Thing/SetThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingServer).SetThing(ctx, req.(*SetThingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Thing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Thing",
	HandlerType: (*ThingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTimeSeriesData",
			Handler:    _Thing_SetTimeSeriesData_Handler,
		},
		{
			MethodName: "SetSensor",
			Handler:    _Thing_SetSensor_Handler,
		},
		{
			MethodName: "SetThing",
			Handler:    _Thing_SetThing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/thing.proto",
}
